[package]
name = "ferris"
version = "0.1.0"
authors = ["Niranjan <blah@abc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.1"
